name: ConditionalActions
version: '${version}'
main: io.github.tanguygab.conditionalactions.ConditionalActions
api-version: 1.20
author: Tanguygab
depend: [PlaceholderAPI]
softdepend: [LuckPerms]
folia-supported: true

commands:
  conditionalactions:
    aliases: [ca]
    permission: conditionalactions.admin